services:
  - type: web
    name: elonu-elon-web
    env: node
    plan: free
    branch: main
    buildCommand: npm install && cd frontend && npm install && npm run build
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001